### ISSUE TITLE
custom name for profiles

### ISSUE THREAD

**Issue by JaspalX** [skydiver/alfred-browsers-profiles#3]
Ideally, for chrome, pull out the chrome profile name from chrome://settings/manageProfile but as I don't think there's an api for that, allow the user to set a custom name for each profile folder....on chrome, choosing between 'person 1', 'person 2' etc. is a bit confusing.

Otherwise, great job :)

**Comment by taylornd** [comment]
I've been looking for a workflow like this for while. Great work. Some of my chrome profiles are pulling the correct profile name but others just Person 1 etc
Brave all pulling correct name. Hopefully this can get sorted or allow a custom name as suggested

**Comment by awsamuel** [comment]
Any insights into what makes Alfred show profile names vs just showing Person 1, Person 2 etc? In the demo screenshots it looks like it's pulling by name but I'm just seeing "Person 1" etc.

**Comment by mwheatfill** [comment]
@awsamuel try changing the name, saving, then changing back to your intended profile name. I noticed the change was not updated in Alfred until I closed Chrome.

**Comment by awsamuel** [comment]
Thanks for that tip!

**Comment by skydiver** [comment]
Hey @awsamuel, this resolved your issue?

**Comment by joeynotjoe** [comment]
I just resolved the issue using the chrome profile rename method, thank you for the tip! ~~Does anyone know what firefox profiles are exactly? I see "default-nightly" "default" and "default-release" 🤔~~ -edit: I realized you can customize profiles in Firefox from the `about:profiles` page. Cheers!
