### ISSUE TITLE
Unable to select profile

### ISSUE THREAD

**Issue by nickokgo** [skydiver/alfred-browsers-profiles#4]
Nothing happens when I type the keyword `bp` into Alfred. Any ideas how to fix?

Many thanks,
Nick

**Comment by lsps9150414** [comment]
@nickokgo reinstall it the 2nd time worked for me somehow

**Comment by nickokgo** [comment]
Hi, thanks for the reply!

I tried reinstalling... and do see initially see it as an option 😃 
<img width="408" alt="SS - Cv0SNuy9" src="https://user-images.githubusercontent.com/18488428/152597338-38a425fd-35b2-4d41-8161-63c630f48bd1.png">

But it disappears soon as I submit the command 😭 
<img width="408" alt="SS - ES99I6Jy" src="https://user-images.githubusercontent.com/18488428/152597676-2c9692ea-20b7-430e-8a8b-5b3dc1b962c1.png">

**Comment by skydiver** [comment]
Hey @nickokgo 
What happens if you run `/usr/bin/env python3` on your console?

**Comment by nickokgo** [comment]
Thanks again. Here's what I get
<img width="570" alt="SS - v6HnCRgW" src="https://user-images.githubusercontent.com/18488428/152656672-97adda9c-e704-436d-be86-e38c01a684b2.png">
