### ISSUE TITLE
Crashes Brave on latest Brave Update

### ISSUE THREAD

**Issue by taylornd** [skydiver/alfred-browsers-profiles#5]
Once Brave has been open a while uses the BP switched crashes all profiles

**Comment by skydiver** [comment]
I can't reproduce the error.
This is my current installed version:

![Screen Shot 2022-02-25 at 20 51 46](https://user-images.githubusercontent.com/578784/155818193-438022a4-2f59-4829-8f1b-cd9237ed54d0.png)

**Comment by taylornd** [comment]
@skydiver  any way I can share crash log or ideas of what else could be causing the issue? If I switch straight away it works fine. But after brave has been open a while it crashed. Looks like another instance of brave opens in the dock

**Comment by skydiver** [comment]
you can try to manually run Brave from the console

first get a profile name then run:
`open -n -a "Brave Browser" --args --profile-directory="PROFILE-NAME"`

**Comment by taylornd** [comment]
That crashes it as well so feels like brave

On March 1, 2022, GitHub ***@***.***> wrote:
> you can try to manually run Brave from the console
>
> first get a profile name then run:
>  open -n -a "Brave Browser" --args --profile-directory="PROFILE-NAME"
>

—
Reply to this email directly, view it on GitHub
<https://github.com/skydiver/alfred-browsers-
profiles/issues/5#issuecomment-1055663032>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AA6MZZY5WHJATZT6UKB76DDU5ZFI3ANCNFSM5O6HCB6A>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
